### ISSUE TITLE
Get Groupsets, Groups and Students in groups

### ISSUE THREAD

**Issue by sdraaijer** [vusaverse/vvcanvas#2]
Hi Tomer,

It would be great if we/you could make a function to extract the Group Sets, Groups and Individuals in Groups from a particular Canvas course.

Hope this would be possible.

Kind regards,

Silvester

**Comment by Tomeriko96** [comment]
Hi Silvester, 

I am not entirely sure what you mean with Group Sets.

For this use case we need the following functions:
- [x] `get_course_groups`
- [x] `get_group_users`

I have written a short vignette showcasing how to use both functions to get groups and their members. 
See: [Vignette: Working with groups](https://vusaverse.github.io/vvcanvas/articles/groups_use_case.html)

Kind regard,

Tomer
