### ISSUE TITLE
Great Package

### ISSUE THREAD

**Issue by cgiannoulis** [vusaverse/vvcanvas#4]
Are you considering using capabilities like this package that is not updated anymore: https://github.com/daranzolin/rcanvas

I am looking for student participation data per course

Thank you 

Chris

**Comment by Tomeriko96** [comment]
Hi Chris,

1410121941d76b783aa7a313095c8b61bbc2e12b Introduces two functions to get participation data for a course. These are `get_course_participation` and `get_student_summaries`.

5d876719ea3fec959c4412c900e5ce57bac0cc4f Introduces a function to get assignment analytics in a course, `get_assignment_data`.

Let me know if these functions answer your issue.

For the time being these functions are only available on the GitHub development version of this package. Expect an update on CRAN somewhere in September.

Kind regards,

Tomer

**Comment by cgiannoulis** [comment]
Amazing! Thank you so very much!!
